### ISSUE TITLE
Server-side `arrays` and `hrefs` don't add anything

### ISSUE THREAD

**Issue by mrecachinas** [LGSInnovations/jupyter-sigplot#11]
I think we can just delete them...

**Comment by RinconResearch** [comment]
They seem to be a record of what has already been added to the plot.  Do we need to keep that state, or should we send all objects to the plot widget regardless of whether they have already been sent?

**Comment by mrecachinas** [comment]
@RinconResearch it depends on what the expected use-cases are for this extension. If we anticipate someone wanting any sort of optimized performance, it would be useful to keep the state so we could determine whether we've already plotted something, and therefore shouldn't replot it.

Jupyter is generally targeted more for after-the-fact analysis and prototyping rather than real-time processing, and therefore, keeping state is a micro-optimization.

Therefore, I think we can safely remove them.

**Comment by mrecachinas** [comment]
Removed in 1d44f0d.
