### ISSUE TITLE
_unravel_path tests are not extensible

### ISSUE THREAD

**Issue by mrecachinas** [LGSInnovations/jupyter-sigplot#19]
@sterre On macOS, `/tmp` is actually a link to `/private/tmp`, so `test_unravel_path` fails.

```
>               assert(actual == expected)
E               AssertionError: assert '/private/tmp' == '/tmp'
E                 - /private/tmp
E                 + /tmp
```

**Comment by mrecachinas** [comment]
The best way I can think to check this is something like
```python
if sys.platform.startswith('darwin'):
    cases.append(("/tmp", "/private/tmp"))
else:
    cases.append(("/tmp", "/tmp"))
```
Let me know your thoughts.

**Comment by mrecachinas** [comment]
See fbbad7e320e51877f7469caa9a20218a7966c3d7. Closing this for now, but if you have any objections, we can re-open.

**Comment by sterre** [comment]
I think that's a fine solution. The real goal was just to check an absolute path, so if there's one that is uniform across all supported platforms, we could just put that in too, in place of `/tmp`. No opinion either way.
