### ISSUE TITLE
"Development Installation" instructions typo

### ISSUE THREAD

**Issue by angelobonet** [LGSInnovations/jupyter-sigplot#2]
* git URL is advertised as: `git clone https://github.com/LGS Innovations/jupyterSigplot.git`
* But the whitespace in `LGS Innovations` appears to be erroneous 
* The URL that worked for me was: `git clone https://github.com/LGSInnovations/jupyterSigplot.git`

**Comment by mrecachinas** [comment]
Fixed in 6f3ba188471f9d8aef77e2435357785de3e25550.
