### ISSUE TITLE
Unicode strings not handled quite right in Python 2 

### ISSUE THREAD

**Issue by sterre** [LGSInnovations/jupyter-sigplot#20]
We have several checks like `isinstance(arg, str)` that return False in Python 2 if the argument is a Unicode string. This happens in practice if you're using Jupyter magics for plotting, and passing the magic argument to `__init__`, `overlay_href`, or `overlay_file`.

You can get the right answer in Python 2 by checking `isinstance(..., basestring)` instead, but the `basestring` type does not exist in Python 3, where all strings are Unicode. Neither does the `unicode` type. 

One way to fix this would be to replace those base `isinstance` calls with calls to a function that makes a version-appropriate check. Another is to have your magic call `str(line)`, which will do the right thing in both Python 2 and Python 3, but at the expense of requiring the magic author to remember to do this.

Recommend we decide how we want to address this (as code or documentation), then implement.

**Comment by mrecachinas** [comment]
Good catch with this. 👍 

In practice, I've preserved Python 2 and 3 compatibility (for string-type checking) with
```python
import sys
py3k = sys.version_info[0] == 3
if py3k:
    StringType = (str, bytes)
else:
    StringType = (basestring, )
...
# u'foo', b'foo', and 'foo' will all return True
# in both Python 2 and 3
if isinstance(my_string, StringType):
    ...
```

**Comment by mrecachinas** [comment]
Closing for now. Let me know if you run into any issues.
