### ISSUE TITLE
Running in MyBinder - Failed to load data

### ISSUE THREAD

**Issue by psychemedia** [LGSInnovations/jupyter-sigplot#21]
Running the MyBinder demo, I get lots of error pop-ups from *hub.mybinder.org* saying:

```
Failed to load data
```

whenever I try to load data in, with the result that the demo notebook does not show off the full range of capabilities of the `SigPlot` package.

**Comment by mrecachinas** [comment]
@psychemedia It should be fixed now. Let us know if you run into any other issues!
