### ISSUE TITLE
`plot.change_settings()` does not appear to modify the plot

### ISSUE THREAD

**Issue by mrecachinas** [LGSInnovations/jupyter-sigplot#37]

**Comment by sterre** [comment]
@ddw saw this in the example Jupyter notebook. The example there was
`plot.change_settings(noxaxis=False, noyaxis=False, xi=True)`

When he traced this down, he found:
* The constructor uses `noxaxis` and `noyaxis`, but `change_settings` uses `show_x_axis` and `show_y_axis`
* `xi` is not supported by `change_settings`

Independent of fixing the example notebook, we may want to unify some of the `plot_init` and `change_settings` logic a bit more to address this.

**Comment by mrecachinas** [comment]
The specific issues addressed here are fixed as best Jupyter-Sigplot is concerned, but we still have #36.

> Independent of fixing the example notebook, we may want to unify some of the `plot_init` and `change_settings` logic a bit more to address this.

If you are referring to `noxaxis` vs `show_x_axis`, that is perhaps better suited as an issue on sigplot itself. It appears at least the `noxaxis` and `noyaxis` have been fixed (see the example notebook).
