### ISSUE TITLE
Remove or fix magics.

### ISSUE THREAD

**Issue by RinconResearch** [LGSInnovations/jupyter-sigplot#38]
The overlay_array, overlay_href, overlay_file, and plot functions all have the @register_line_cell_magic decorator, but they don't actually seem to work as magics.  They should be fixed or removed.

**Comment by mrecachinas** [comment]
I have no real preference here, but I'm leaning toward removing them. What are your thoughts @RinconResearch @sterre @maihde?

**Comment by sterre** [comment]
I'd say we should remove them. I don't understand how they are intended to work (what instance would a given magic affect?). They also feel a bit out of place for magics--compared to everything else in `%lsmagic`, they seem to be on a different level (those magics mostly operate on the kernel/notebook itself, or connect to the environment). 

In future, we may well come up with a nice `%plot` or `%%plot` magic that simplifies syntax, but at the present stage of the game, I don't feel like we know enough about use cases to design an effective SigPlot magic.
