### ISSUE TITLE
Version 0.1.1 of the extension does not import because it references removed example module

### ISSUE THREAD

**Issue by sterre** [LGSInnovations/jupyter-sigplot#5]
There's still an import from the removed `example` module in `__init__.py` that prevents successful import of `jupyter_sigplot` at version 0.1.1:

https://github.com/LGSInnovations/jupyter-sigplot/blob/f0580d4539f7ce778a1ff2e725dc49d4aac9c200/jupyter_sigplot/__init__.py#L5

Removing this line allows successful import and instantiation of a widget.

It seems likely that testing was done in a clone that still had the removed module in place, suggesting an opportunity for automated testing.

**Comment by mrecachinas** [comment]
Good catch. Thanks @sterre!

**Comment by mrecachinas** [comment]
Will setup Travis-CI and push to pip after. Hope to get that tonight or tomorrow.
